### ISSUE TITLE
Finish Gui

### ISSUE THREAD

**Issue by Niko4u5** [IQuadratC/P5#6]

**Comment by Stoby241** [comment]
Die Steuerung für den HI Roboter muss noch gefixed und getestet werden

**Comment by Niko4u5** [comment]
Die HI Steuerung wurde gefvxed

**Comment by Niko4u5** [comment]
Die Slider und der Joystick haben noch keine Graphick

**Comment by Niko4u5** [comment]
Die Slider haben noch keine Grafik
